### ISSUE TITLE
Couldn't open ./data/mnc_model/mnc_model.caffemodel.h5

### ISSUE THREAD

**Issue by ne-v0y** [daijifeng001/MNC#28]
I am very new to caffe and mnc, and was trying to run the demo, but received error like below
(only error log that is after Network initialization done was copied). I was wondering if there is anything to do with GPU since I modified the code and ran the cup mode, but I'm not sure... really new to this. Really appreciate it if anyone can help me out of this!

> I1204 16:42:29.921504 32654 net.cpp:283] Network initialization done.
HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140144062981952:
  #000: ../../../src/H5F.c line 1586 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5F.c line 1377 in H5F_open(): unable to read superblock
    major: File accessibilty
    minor: Read failed
  #002: ../../../src/H5Fsuper.c line 334 in H5F_super_read(): unable to find file signature
    major: File accessibilty
    minor: Not an HDF5 file
  #003: ../../../src/H5Fsuper.c line 155 in H5F_locate_signature(): unable to find a valid file signature
    major: Low-level I/O
    minor: Unable to initialize object
F1204 16:42:29.922904 32654 net.cpp:858] Check failed: file_hid >= 0 (-1 vs. 0) Couldn't open ./data/mnc_model/mnc_model.caffemodel.h5
*** Check failure stack trace: ***
Aborted (core dumped)

>

**Comment by Oh233** [comment]
@ne-v0y This is due to my careless mistake in the download URL, which leads to an invalid h5 file. This is fixed in https://github.com/daijifeng001/MNC/commit/99410889179f2da71b9e3d4d6ceb8503371c5ab9.

Thanks for your information. Sorry for the inconvenience it caused.

**Comment by blessxu** [comment]
I still encounter this problem, after download the file, I got a 404.
